skip-check:
  - CKV_TF_1         # Skip check for missing provider version
  - CKV_TF_2         # Skip check for module source not using pinned version (e.g. ref=main)
download-external-modules: true
