name: Auto Approve

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve:
    uses: your-org/your-repo/.github/workflows/reusable/github/auto-approve.yml@main
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
