name: PR Terraform Check

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  terraform-fmt:
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_fmt.yml@main
    with:
      terraform-directory: .

  terraform-validate:
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_validate.yml@main
    with:
      terraform-directory: .

  terraform-tflint:
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_tflint.yml@main
    with:
      terraform-directory: .

  terraform-checkov:
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_checkov.yml@main
    with:
      terraform-directory: .
