name: PR Terraform Check

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  terraform-fmt:
    uses: thecloudsolutions/github-actions/.github/workflows/fmt.yml@main
    with:
      terraform-directory: .
