name: PR Terraform Check

on:
  pull_request:

jobs:
  terraform-structure:
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_structure.yml@main
    with:
      terraform-directory: .
      
  terraform-docs:
    needs: terraform-structure
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_docs.yml@main
    with:
      terraform-directory: .
      
  terraform-fmt:
    needs: terraform-docs
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_fmt.yml@main
    with:
      terraform-directory: .

  terraform-validate:
    needs: terraform-fmt
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_validate.yml@main
    with:
      terraform-directory: .

  terraform-tflint:  
    #TODO: add needs when repos are public
    #needs: terraform-validate
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_tflint.yml@main
    with:
      terraform-directory: .
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  terraform-checkov:
    ##TODO: add needs when repos are public
    #needs: terraform-validate
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_checkov.yml@main
    with:
      terraform-directory: .
