name: Terraform PR Check

on:
  pull_request:

permissions:
  contents: read
  
jobs:
  terraform-structure:
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_structure.yml@main
      
  terraform-docs:
    needs: terraform-structure
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_docs.yml@main
      
  terraform-format:
    needs: terraform-docs
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_format.yml@main

  terraform-validate:
    needs: terraform-format
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_validate.yml@main

  terraform-tflint:  
    needs: terraform-validate
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_tflint.yml@main

  terraform-checkov:
    needs: terraform-validate
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_checkov.yml@main
