name: Terraform PR Check
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
  
jobs:
  terraform-structure:
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_structure.yml@main
      
  terraform-docs:
    needs: terraform-structure
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_docs.yml@main
      
  terraform-format:
    needs: terraform-docs
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_format.yml@main
    
  terraform-validate:
    needs: terraform-format
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_validate.yml@main
    
  terraform-tflint:  
    needs: terraform-validate
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_tflint.yml@main
    
  terraform-checkov:
    needs: terraform-validate
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_checkov.yml@main

  terraform-comment:
    needs: [terraform-structure, terraform-docs, terraform-format, terraform-validate, terraform-tflint, terraform-checkov]
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_comment.yml@main
    with:
      step-name: "All Terraform Validations"
      step-result: "success"
      success-message: "🎉 All checks passed! Your PR is ready to merge! 🚀\n\n✅ Structure validation\n✅ Documentation validation\n✅ Format validation\n✅ Terraform validation\n✅ TFLint validation\n✅ Checkov security scan"