name: Terraform PR Check
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
  
jobs:
  terraform-structure:
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-structure.yml@main
      
  terraform-docs:
    needs: terraform-structure
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-docs.yml@main
      
  terraform-format:
    needs: terraform-docs
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-format.yml@main
    
  terraform-validate:
    needs: terraform-format
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-validate.yml@main
    
  terraform-tflint:  
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-tflint.yml@main
    
  terraform-checkov:
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-checkov.yml@main

  terraform-comment:
    needs: [terraform-structure, terraform-docs, terraform-format, terraform-validate, terraform-tflint, terraform-checkov]
    if: always()  # ← Missing this
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-comment.yml@main
    with:
      step-name: "Infrastructure Validation Summary"  # ← Updated name
      step-result: ${{ (needs.terraform-structure.result == 'success' && needs.terraform-docs.result == 'success' && needs.terraform-format.result == 'success' && needs.terraform-validate.result == 'success' && needs.terraform-tflint.result == 'success' && needs.terraform-checkov.result == 'success') && 'success' || 'failure' }}  # ← Dynamic calculation
      success-message: "🎉 All infrastructure code checks passed! Your Terraform changes are ready to deploy! 🚀\\n\\n✅ File naming conventions\\n✅ Documentation is current\\n✅ Code formatting\\n✅ Syntax validation\\n✅ Code quality (TFLint)\\n✅ Security scan (Checkov)"
      failure-message: "Infrastructure validation incomplete. Review the specific failed checks above and fix the issues before deploying."  # ← Missing this
