name: Makefile Validation

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."

permissions:
  contents: read
  pull-requests: write

jobs:
  makefile-validate:
    name: Validate Makefiles
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.makefile-validation.outcome }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y make shellcheck

      - name: Validate Makefiles
        id: makefile-validation
        working-directory: ${{ inputs.working-directory }}
        run: |
          set -e
          
          if ! find . -name "Makefile" -o -name "*.mk" | grep -q .; then
            echo "No Makefiles found - skipping validation"
            exit 0
          fi
          
          echo "Checking Makefile syntax..."
          if ! make -qp >/tmp/make_output 2>&1; then
            echo "Makefile parsing failed:"
            cat /tmp/make_output
            exit 1
          fi
          
          echo "Checking shell scripts..."
          scripts=$(find . -name "*.sh" -type f || true)
          if [ -n "$scripts" ]; then
            shellcheck $scripts
          fi
          
          echo "Makefile validation passed"

  comment:
    needs: makefile-validate
    if: always()
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-comment.yml@main
    with:
      step-name: "Build System Check (Makefile)"
      step-result: ${{ needs.makefile-validate.outputs.result }}
      success-message: "Makefile syntax is valid and shell scripts pass linting."
      failure-message: "Makefile issues detected. Check the logs for specific errors."
