name: Makefile Validation

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  makefile-validate:
    name: Validate Makefiles
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.makefile-validation.outcome }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Makefiles
        id: makefile-validation
        run: |
          if find . -name "Makefile" -o -name "*.mk" | grep -q .; then
            make -n >/dev/null 2>&1 || {
              echo "Makefile syntax error";
              exit 1;
            }
          fi

  # comment:
  #   needs: makefile-validate
  #   if: always()
  #   uses: thecloudsolutions/github-actions/.github/workflows/terraform-comment.yml@main
  #   with:
  #     step-name: "Build System Check (Makefile)"
  #     step-result: ${{ needs.makefile-validate.outputs.result }}
  #     success-message: "Makefile syntax is valid."
  #     failure-message: "Makefile issues detected. Check the logs for specific errors."
