name: Validate Terraform Docs

on:
  workflow_call:
    inputs:
      terraform-directory:
        required: false
        type: string
        default: "."

permissions:
  contents: read
  
jobs:
  validate-docs:
    name: Validate Terraform Docs
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.docs-validation.outcome }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate generated Terraform docs
        id: docs-validation
        working-directory: ${{ inputs.terraform-directory }}
        run: |
          cp README.md README.md.original
          make readme
          if ! diff -q README.md.original README.md; then
            diff -u README.md.original README.md
            echo "README.md is out of date. Please run 'make readme'."
            exit 1
          fi

  comment:
    needs: validate-docs
    if: always()
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-comment.yml@main
    with:
      step-name: "Terraform Documentation Validation"
      step-result: ${{ needs.validate-docs.outputs.result }}
      success-message: "Documentation is up to date."
      failure-message: "Documentation is out of date. Please run `make readme` and commit the changes."