name: Terraform Checkov

on:
  workflow_call:
    inputs:
      terraform-directory:
        required: false
        type: string
        default: "."

permissions:
  contents: read

jobs:
  checkov:
    name: Run Checkov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: pip install checkov

      - name: Download centralized Checkov config
        run: |
          curl -sSL \
            https://raw.githubusercontent.com/thecloudsolutions/github-actions/main/.github/configs/.checkov.yml \
            -o .checkov.yml

      - name: Download custom policy
        run: |
          mkdir -p configs/checkov
          curl -sSL \
            https://raw.githubusercontent.com/thecloudsolutions/github-actions/main/.github/configs/no_direct_resource_usage.yaml \
            -o configs/checkov/no_direct_resource_usage.yml

      - name: Run Checkov with config and custom policies
        run: |
          checkov -d "${{ inputs.terraform-directory }}" \
            --config-file .checkov.yml \
            --external-checks-dir configs/checkov \
            --compact \
            --download-external-modules true
