name: Validate Terraform Structure

on:
  workflow_call:
    inputs:
      terraform-directory:
        required: false
        type: string
        default: "."

jobs:
  enforce-file-names:
    name: "Enforce allowed Terraform file names"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Terraform filenames
        run: |
          echo "Checking for disallowed .tf files."
          allowed_files=("main.tf" "variables.tf" "outputs.tf" "data.tf" "locals.tf")

          disallowed_files=$(find . -type f -name "*.tf" | while read file; do
            fname=$(basename "$file")
            if [[ ! " ${allowed_files[@]} " =~ " ${fname} " ]]; then
              echo "$file"
            fi
          done)

          if [[ -n "$disallowed_files" ]]; then
            echo "The following .tf files are not allowed:"
            echo "$disallowed_files"
            exit 1
          else
            echo "All .tf files are allowed."
          fi
          
