name: Terraform Checkov

on:
  workflow_call:
    inputs:
      terraform-directory:
        required: false
        type: string
        default: "."

permissions:
  contents: read
  id-token: write

jobs:
  checkov:
    name: Run Checkov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: pip install checkov

      - name: Download centralized Checkov config
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          curl -sSL -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3.raw" \
            https://api.github.com/repos/thecloudsolutions/github-actions/contents/.github/configs/.checkov.yml \
            -o .checkov.yml

      - name: Run Checkov with custom policy
        run: |
          checkov -d "${{ inputs.terraform-directory }}" \
            --external-checks-dir configs/checkov \
            --compact \
            --download-external-modules true
