name: Terraform PR Comment
on:
  workflow_call:
    inputs:
      step-name:
        required: true
        type: string
        description: "Name of the validation step"
      step-result:
        required: true
        type: string
        description: "Result of the step (success or failure)"
      success-message:
        required: false
        type: string
        default: "Validation passed successfully."
        description: "Message to show on success"
      failure-message:
        required: false
        type: string
        default: "Validation failed. Please check the logs for details."
        description: "Message to show on failure"

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    name: Add PR Comment
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR - Success
        if: inputs.step-result == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **${{ inputs.step-name }} Passed** - ${{ inputs.success-message }}`
            })
      
      - name: Comment on PR - Failure  
        if: inputs.step-result == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ **${{ inputs.step-name }} Failed** - ${{ inputs.failure-message }}`
            })