name: Terraform validate

on:
  workflow_call:
    inputs:
      terraform-directory:
        required: false
        type: string
        default: "."

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-validate:
    name: Run terraform validate
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.validate-check.outcome }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5
        
      - name: Run terraform validate recursively
        id: validate-check
        run: |
          find . -type d | while read dir; do
            if ls "$dir"/*.tf > /dev/null 2>&1; then
              echo "Validating in $dir"
              (
                cd "$dir"
          
                echo "Running terraform init in $dir"
                terraform init -backend=false -input=false
          
                echo "Running terraform validate in $dir"
                terraform validate -no-color
              )
              echo ""
            fi
          done

  comment:
    needs: terraform-validate
    if: always()
    uses: thecloudsolutions/github-actions/.github/workflows/terraform_comment.yml@main
    with:
      step-name: "Terraform Validation"
      step-result: ${{ needs.terraform-validate.outputs.result }}
      success-message: "Configuration is valid."
      failure-message: "Terraform configuration is invalid. Please run `terraform validate` locally and fix the issues."
