name: Terraform format

on:
  workflow_call:
    inputs:
      terraform-directory:
        required: false
        type: string
        default: "."

jobs:
  terraform-format:
    name: Run terraform format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5

      - name: Run terraform format
        run: terraform fmt -recursive "${{ inputs.terraform-directory }}"
