name: Terraform format

on:
  workflow_call:
    inputs:
      terraform-directory:
        required: false
        type: string
        default: "."
permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-format:
    name: Run terraform format
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.format-check.outcome }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5

      - name: Run terraform format
        id: format-check
        run: terraform fmt -recursive "${{ inputs.terraform-directory }}"

  comment:
    needs: terraform-format
    if: always()
    uses: thecloudsolutions/github-actions/.github/workflows/terraform-comment.yml@main
    with:
      step-name: "Terraform Format Validation"
      step-result: ${{ needs.terraform-format.outputs.result }}
      success-message: "Code is properly formatted."
      failure-message: "Code formatting issues found. Please run `terraform fmt` to fix formatting."